### ISSUE TITLE
headCount function: roleArray seems to sometimes return an empty array even if there are creeps

### ISSUE THREAD

**Issue by quonic** [bonzaiferroni/bonzAI#2]
Misson.ts: function headCount

I found this through UpgradeMission.ts: Line 129 and this.linkUpgraders is sometimes an empty array even if there where upgraders already spawned.

Adding this to above `return roleArray;` line 119 of Mission.ts
```
if(roleName == "upgrader"){
    console.log(`Test ${roleArray}`);
}
```

Gets this:

> [1:34:36 PM]Test 
> [1:34:36 PM]Test 
> [1:34:36 PM]Test [creep uBase1_upgrader_38]
> [1:34:36 PM]Test [creep zBase1_upgrader_24],[creep zBase1_upgrader_57]

Upgraders are spawned for the two lines that don't have creeps, but they don't take further actions once spawned.

**Comment by bonzaiferroni** [comment]
Good observation! Although this is expected behavior.

There is some stuff happening under the hood on headCount that might mean they aren't automatically returned even after they are spawned. The purpose of headCount is to give you your ready-to-be-used creeps, but sometimes you will want to do things first before you use them, like give them boosts or have them follow some waypoints. All this happens in the `mission.prepCreep(creep)` function that gets called within headCount on [line 91](https://github.com/bonzaiferroni/bonzAI/blob/4531d3d62d05e7bc763aad9be45290216d61e9d4/src/Mission.ts#L91). When prepCreep returns true, that means the creep starts getting added to the roleArray value. So for at least the first few ticks of a creeps existence, it is checking the creep for preparadness. For creeps that don't have any extra prep behavior defined, this will happen even before they are finished being spawned.

**Comment by bonzaiferroni** [comment]
This makes boosting your creeps as easy as adding the boosts as a parameter on headCount. Here is how linkUpgrader uses headCount:

```typescript
this.linkUpgraders = this.headCount("upgrader", linkUpgraderBody, max, {
            prespawn: this.distanceToSpawn,
            memory: memory,
            moveToRoom: true} );
```

earlier in the function you can see the logic that determines whether they will be boosted, which is part of the `memory` value being used:

```typescript
let memory;
if (this.boost || this.empire.hasAbundance(RESOURCE_CATALYZED_GHODIUM_ACID, RESERVE_AMOUNT * 2)) {
    memory = {boosts: [RESOURCE_CATALYZED_GHODIUM_ACID], allowUnboosted: this.allowUnboosted};
}
```

The boost gets automatically loaded in a lab when a creep is spawning with a boost in memory. Then the creep uses `creep.seekBoost` during the prep phase to get boosted. Since `allowUnboosted` will almost always evaluate to true, the creep will just move on if there isn't a boost ready.
